' WITH CombinedDatas AS ('
+ '     WITH CombinedData AS ('
+ '         SELECT '
+ '             o.vstdate AS dates, '
+ '             o.vn AS visit_id, '
+ '             p.hn,  '
+ '             CONCAT(p.pname, p.fname, " ", p.lname) AS patient_name, '
+ '             STRING_AGG(od.icd10, ", ") AS icd10'
+ '         FROM ovst o'
+ '         LEFT OUTER JOIN ovstdiag od ON od.vn = o.vn'
+ '         LEFT OUTER JOIN patient p ON p.hn = o.hn'
+ '         WHERE o.vstdate BETWEEN "2022-10-01" AND "2023-09-30"'
+ '         AND od.icd10 BETWEEN "C50" AND "C509"'
+ '         AND o.an IS NULL'
+ '         GROUP BY o.vstdate, o.vn, p.hn, p.pname, p.fname, p.lname'

+ '         UNION ALL'

+ '         SELECT '
+ '             i.dchdate AS dates, '
+ '             i.an AS visit_id, '
+ '             p.hn,  '
+ '             CONCAT(p.pname, p.fname, " ", p.lname) AS patient_name, '
+ '             STRING_AGG(id.icd10, ", ") AS icd10'
+ '         FROM ipt i'
+ '         LEFT OUTER JOIN iptdiag id ON id.an = i.an'
+ '         LEFT OUTER JOIN patient p ON p.hn = i.hn'
+ '         WHERE i.dchdate BETWEEN "2022-10-01" AND "2023-09-30" '
+ '         AND id.icd10 BETWEEN "C50" AND "C509"'
+ '         GROUP BY i.dchdate, i.an, p.hn, p.pname, p.fname, p.lname'
+ '     )'
+ '     SELECT DISTINCT ON (hn) *'
+ '     FROM CombinedData'
+ '     ORDER BY hn, dates DESC'
+ '     )'
+ ' SELECT *'
+ ' FROM CombinedDatas'
+ ' ORDER BY dates '
