' SELECT reout.vn, reout.refer_date,' 
+ ' reout.hn, '
+ ' Concat(p.pname, p.fname, " ", p.lname) AS name, '
+ ' hos.name AS hosname, '
+ ' reout.pdx, '
+ ' pt.name AS name1, '
+ ' reout.department, '
+ ' cc.cc, '
+ ' d.name AS name2, '
+ ' reout.accept_point '
+ ' FROM referout reout '
+ ' LEFT JOIN ovst o ON o.vn = reout.vn OR o.an = reout.vn '
+ ' LEFT JOIN patient p ON p.hn = reout.hn '
+ ' LEFT JOIN hospcode hos ON hos.hospcode = reout.refer_hospcode '
+ ' LEFT JOIN pttype pt ON pt.pttype = reout.pttype '
+ ' LEFT JOIN opdscreen cc ON cc.vn = o.vn '
+ ' LEFT JOIN doctor d ON d.code = reout.doctor '
+ ' WHERE reout.refer_date BETWEEN "'+ds1+'" AND "'+ds2+'" '
+ ' ORDER BY reout.refer_date'
