' SELECT '
+ '     o.vstdate, '
+ '     o.vn,'
+ '     p.hn, '
+ '     p.cid, '
+ '     CONCAT(p.pname, p.fname, " ", p.lname) AS patient_name,'
+ '     op.pttype,'
+ '     sum(op.sum_price) as cost,'
+ '     COALESCE(vv.income, 0.00) AS income,'
+ '     COALESCE(vv.uc_money, 0.00) AS ลูกหนี้,'
+ '     COALESCE(vv.paid_money, 0.00) AS ต้องชำระ,'
+ '     coalesce(rc.total_amount,0.00) as ชำระ,'
+ '     CASE WHEN vv.remain_money = 0 THEN COALESCE(vv.paid_money, 0.00) - coalesce(rc.total_amount,0.00) END AS ค้างชำระ ,'
+ '     op.paidst'
+ ' FROM ovst o'
+ ' LEFT OUTER JOIN opitemrece op ON op.vn = o.vn '
+ ' LEFT OUTER JOIN xray_items x ON x.icode = op.icode '
+ ' LEFT OUTER JOIN patient p ON p.hn = o.hn'
+ ' LEFT OUTER JOIN (select vn, sum(total_amount) as total_amount, rtrim(string_agg(rcpno, E",\n"), ",") as rcpno, RTrim(String_Agg(DISTINCT To_Char(rcpt_print.bill_date, "DD/MM/") || (Extract(YEAR FROM rcpt_print.bill_date) + 543), E",\n"), ",") AS bill_date, rtrim(string_agg(DISTINCT bill_staff, E",\n"), ",") as bill_staff from rcpt_print where status = "OK" and department = "OPD" group by vn) rc ON o.vn = rc.vn'
+ ' LEFT OUTER JOIN vn_stat vv ON vv.vn = o.vn'
+ ' WHERE o.vstdate BETWEEN "2025-01-01" AND "2025-01-31" '
+ ' AND xray_items_group = "3" AND x.active_status = "Y" '
+ ' AND (op.pttype BETWEEN "H1" AND "H5" '
+ ' OR op.pttype IN ("I2") '
+ ' OR op.pttype LIKE"A%" '
+ ' OR op.pttype LIKE"B%" '
+ ' OR op.pttype LIKE"O%" '
+ ' OR op.pttype LIKE"L%")'
+ ' GROUP BY o.vstdate, o.vn, p.hn,p.cid, p.pname, p.fname, p.lname, op.pttype, op.paidst, rc.total_amount ,vv.income, vv.uc_money, vv.paid_money, vv.remain_money'