+ ' SELECT '
+ '     p.hn, '
+ '     p.cid,'
+ '     CONCAT(p.pname, " ", p.fname, " ", p.lname) AS patient_name, '
+ '     EXTRACT(YEAR FROM AGE(CURRENT_DATE, p.birthday)) AS age,'
+ '     p.addrpart,'
+ '     p.moopart, '
+ '     p.tmbpart,'
+ '     p.amppart,'
+ '     p.chwpart,'
+ '     th.full_name,'
+ '     o.report_date,'
+ '     o.begin_date,'
+ '     o.agent,'
+ '     o.symptom,'
+ '     re.relation_name,'
+ '     se.seiousness_name,'
+ '     o.note'
+ ' FROM opd_allergy o'
+ ' INNER JOIN patient p ON p.hn = o.hn '
+ ' LEFT OUTER JOIN thaiaddress th ON th.chwpart = p.chwpart AND th.amppart = p.amppart AND th.tmbpart = p.tmbpart'
+ ' LEFT OUTER JOIN allergy_relation re ON re.allergy_relation_id = o.allergy_relation_id'
+ ' LEFT OUTER JOIN allergy_seriousness se ON se.seriousness_id = o.seriousness_id'
+ ' WHERE o.report_date BETWEEN "'+ds1+'" AND "'+ds2+'"'
+ ' GROUP BY p.hn, p.cid, p.pname, p.fname, p.lname, p.birthday, p.addrpart,'
+ ' p.moopart, p.tmbpart, p.amppart, p.chwpart, th.full_name, o.report_date, o.begin_date,o.agent, o.symptom, re.relation_name, se.seiousness_name, o.note'
+ ' ORDER BY report_date'