' SELECT '
+ '     prev_visit.vstdate AS previous_vstdate,'
+ '     prev_visit.vsttime AS previous_vsttime,'
+ '     p.hn, '
+ '     p.cid, '
+ '     CONCAT(p.pname, p.fname, " ", p.lname) AS patient_name,'
+ '     COALESCE(prev_visit.pe, "-") AS previous_pe,'
+ '     o.vstdate AS current_vstdate,'
+ '     o.vsttime AS current_vsttime,'
+ '     COALESCE(os.pe, "-") AS current_pe,  '
+ '     vv.pdx, '
+ '     vv.lastvisit_hour, '
+ '     er.vn,'
+ '     l.er_leave_status_name'
+ ' FROM ovst o'
+ ' INNER JOIN er_regist er ON er.vn = o.vn'
+ ' LEFT JOIN er_leave_status l ON l.er_leave_status_id = er.er_leave_status_id'
+ ' LEFT JOIN vn_stat vv ON o.vn = vv.vn'
+ ' LEFT JOIN patient p ON p.hn = o.hn'
+ ' LEFT JOIN opdscreen os ON os.vn = o.vn'
+ ' LEFT JOIN ('
+ '     SELECT o2.hn, o2.vn, o2.vstdate, o2.vsttime, os2.pe'
+ '     FROM ovst o2'
+ '     JOIN vn_stat v2 ON o2.vn = v2.vn'
+ '     LEFT JOIN opdscreen os2 ON os2.vn = o2.vn'
+ ' ) prev_visit ON prev_visit.hn = p.hn  '
+ ' AND prev_visit.vstdate < o.vstdate '
+ ' AND (o.vstdate + o.vsttime - (prev_visit.vstdate + prev_visit.vsttime)) <= INTERVAL "48 hours"'
+ ' AND prev_visit.vn IN ('
+ '     SELECT o2.vn'
+ '     FROM ovst o2'
+ '     JOIN vn_stat v2 ON o2.vn = v2.vn'
+ '     WHERE o2.hn = p.hn'
+ '     AND o2.vstdate < o.vstdate'
+ '     AND (o.vstdate + o.vsttime - (o2.vstdate + o2.vsttime)) <= INTERVAL "48 hours"'
+ '     AND v2.pdx = vv.pdx'
+ '     ORDER BY o2.vstdate DESC, o2.vsttime DESC'
+ '     LIMIT 1'
+ ' )'

+ ' WHERE o.vstdate BETWEEN "'+ds1+'" AND "'+ds2+'" '
+ ' AND vv.lastvisit_hour <> 0 '
+ ' AND vv.lastvisit_hour <= 48'
+ ' AND EXISTS ('
+ '     SELECT 1 '
+ '     FROM vn_stat v2'
+ '     JOIN ovst o2 ON o2.vn = v2.vn'
+ '     WHERE v2.hn = vv.hn  '
+ '     AND o2.vstdate < o.vstdate '
+ '     AND (o.vstdate + o.vsttime - (o2.vstdate + o2.vsttime)) <= INTERVAL "48 hours"'
+ '     AND v2.pdx = vv.pdx'
+ ' )'
