ChangeReportSQL('WITH DepartmentGroups AS ( '
      + '    SELECT '
      + '        o.vn,'
      + '        CASE '
      + '            WHEN o.main_dep IN ("010", "014", "016", "098", "112", "138") THEN "OPD (จุดซักประวัติ)" '
      + '            WHEN o.main_dep IN ("029", "117") THEN "กุมารเวชกรรม" '
      + '            WHEN o.main_dep IN ("031", "120") THEN "จักษุ" '
      + '            WHEN o.main_dep IN ("034", "037", "050") THEN "จิตเวช" '
      + '            WHEN o.main_dep = "005" THEN "ทันตกรรม" '
      + '            WHEN o.main_dep IN ("048", "118", "119") THEN "ฝากครรภ์ (ANC)" '
      + '            WHEN o.main_dep = "012" THEN "Ultrasound"' 
      + '            WHEN o.main_dep IN ("080", "104", "144") THEN "ศัลยกรรม" '
      + '            WHEN o.main_dep IN ("032", "105", "132", "143") THEN "ศัลยกรรมกระดูก" '
      + '            WHEN o.main_dep IN ("081", "114") THEN "สูติ- นรีเวชกรรม" '
      + '            WHEN o.main_dep IN ("001", "026", "053", "054", "055", "102", "137", "154", "101", "103", "106", "001", "002", "003", "121", "122", "123", "137") THEN "NCD (อายุรกรรม)" '
      + '            WHEN o.main_dep IN ("042", "131") THEN "เวชกรรมฟื้นฟู (กายภาพ)" '
      + '            WHEN o.main_dep = "011" THEN "เวชศาสตร์ฉุกเฉินและนิติเวช (ER)" '
      + '            WHEN o.main_dep IN ("041", "134") THEN "แพทย์แผนไทย" '
      + '            WHEN o.main_dep = "130" THEN "CT SCAN" '
      + '            WHEN o.main_dep IN ("045", "124") THEN "ARV" '
      + '            WHEN o.main_dep = "007" THEN "Lab (จากรพ.ดอนสัก)" '
      + '            WHEN o.main_dep = "040" THEN "ทำแผล ฉีดยา" '
      + '            WHEN o.main_dep IN ("041", "135") THEN "แพทย์แผนจีน" '
      + '            WHEN o.main_dep = "058" THEN "ห้องตรวจวัณโรค" '
      + '            WHEN o.main_dep IN ("017", "049", "052", "091") THEN "อื่นๆ" '
      + '            ELSE "อื่นๆ" '
      + '        END AS group_name'
      + '    FROM ovst o '
      + '    WHERE o.vstdate BETWEEN "'+ds1+'" AND "'+ds2+'" AND o.an IS NULL'
      + ')'
      
      + 'SELECT '
      + '    group_name,'
      + '    COUNT(vn)  AS visit_count '
      + 'FROM DepartmentGroups '
      + 'GROUP BY group_name '
      + 'ORDER BY '
      + '    CASE '
      + '        WHEN group_name = "OPD (จุดซักประวัติ)" THEN 1 '
      + '        WHEN group_name = "กุมารเวชกรรม" THEN 2 '
      + '        WHEN group_name = "จักษุ" THEN 7 '
      + '        WHEN group_name = "จิตเวช" THEN 12 '
      + '        WHEN group_name = "ทันตกรรม" THEN 11 '
      + '        WHEN group_name = "ฝากครรภ์ (ANC)" THEN 5 '
      + '        WHEN group_name = "Ultrasound" THEN 15 '
      + '        WHEN group_name = "ศัลยกรรม" THEN 3 '
      + '        WHEN group_name = "ศัลยกรรมกระดูก" THEN 4 '
      + '        WHEN group_name = "สูติ- นรีเวชกรรม" THEN 6 '
      + '        WHEN group_name = "NCD (อายุรกรรม)" THEN 10 '
      + '        WHEN group_name = "เวชกรรมฟื้นฟู (กายภาพ)" THEN 18 '
      + '        WHEN group_name = "เวชศาสตร์ฉุกเฉินและนิติเวช (ER)" THEN 9 '
      + '        WHEN group_name = "แพทย์แผนไทย" THEN 19 '
      + '        WHEN group_name = "CT SCAN" THEN 16 '
      + '        WHEN group_name = "ARV" THEN 13 '
      + '        WHEN group_name = "Lab (จากรพ.ดอนสัก)" THEN 17 '
      + '        WHEN group_name = "ทำแผล ฉีดยา" THEN 8 '
      + '        WHEN group_name = "แพทย์แผนจีน" THEN 20 '
      + '        WHEN group_name = "ห้องตรวจวัณโรค" THEN 14'
      + '        ELSE 21 '
      + '    END ');