+ ' TO_CHAR(oi.vstdate + INTERVAL "543 years", "DD/MM/YYYY") AS date '
+ ' FROM ovst oi'
+ ' LEFT OUTER JOIN ovstdiag oid ON oid.vn = oi.vn'
+ ' LEFT OUTER JOIN patient p ON p.hn = oi.hn'
+ ' LEFT OUTER JOIN vn_stat van ON van.vn = oi.vn'
+ ' LEFT OUTER JOIN nationality n ON n.nationality = p.nationality'
+ ' LEFT OUTER JOIN occupation oc ON oc.occupation = p.occupation'
+ ' LEFT OUTER JOIN thaiaddress th ON th.chwpart = p.chwpart AND th.amppart = p.amppart AND th.tmbpart = p.tmbpart'
+ ' WHERE oi.vstdate BETWEEN "'+ds1+'" AND "'+ds2+'" AND oi.an IS NULL'
+ ' AND (oid.icd10 BETWEEN "A54" AND "A549" OR oid.icd10 IN ("K671", "M730", "N743", "O982"))'
+ ' GROUP BY  p.hn, p.cid, van.age_y, van.age_m, van.age_d, n.name, oc.name, oid.icd10, p.pname, '
+ ' p.fname, p.lname, p.sex, p.informaddr, p.addrpart, p.moopart, th.full_name, oi.vstdate'
+ ' ORDER BY oi.vstdate'

+ ' TO_CHAR(oid.modify_datetime + INTERVAL "543 years", "DD/MM/YYYY HH24:MI:SS") AS date'
+ ' FROM ipt oi '
+ ' LEFT OUTER JOIN iptdiag oid ON oid.an = oi.an'
+ ' LEFT OUTER JOIN patient p ON p.hn = oi.hn'
+ ' LEFT OUTER JOIN an_stat van ON van.an = oi.an'
+ ' LEFT OUTER JOIN nationality n ON n.nationality = p.nationality'
+ ' LEFT OUTER JOIN occupation oc ON oc.occupation = p.occupation'
+ ' LEFT OUTER JOIN thaiaddress th ON th.chwpart = p.chwpart AND th.amppart = p.amppart AND th.tmbpart = p.tmbpart'
+ ' WHERE oi.dchdate BETWEEN "'+ds1+'" AND "'+ds2+'"'
+ ' AND (oid.icd10 BETWEEN "A54" AND "A549" OR oid.icd10 IN ("K671", "M730", "N743", "O982"))'
+ ' GROUP BY  oi.hn, p.cid, van.age_y, van.age_m, van.age_d, n.name, oc.name, oid.modify_datetime,  '
+ ' oid.icd10, p.pname, p.fname, p.lname, p.sex, p.informaddr, p.addrpart, p.moopart, th.full_name, oi.dchdate '
+ ' ORDER BY oi.dchdate '